# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: Clean Code
description: "A blog about good programming practices"
keywords: "programming, clean code, architect, software, "

# Site settings
url: http://jordiferm.github.io
#baseurl: "/dotX"
baseurl: ""

# Author settings
author:
  name      : Jordi Fernàndez Monteis
  job       : Senior Software Engineer at Hpe
  bio       : "Application developer, software engineer, and software architect with 20+ years of experience in a wide variety of business applications."
  thumb     : /images/author.jpg
  email     : j@softtopia.com
  url       : http://jordiferm.github.io
  github    : http://github.com/jordiferm
  twitter   : http://twitter.com/jordiferm
  linkedin  : https://es.linkedin.com/in/jordi-fernàndez-0056751b

# google_analytics: UA-52446115-1
repo: http://github.com/jordiferm/dotX

# comments
disqus_shortname: "jordiferm"
